services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    build:
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.1}
  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - '9025:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: >
      --enable-feature=remote-write-receiver
      --enable-feature=exemplar-storage
      --enable-feature=native-histograms
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
