apiVersion: 1

datasources:
  - name: gdev-testdata
    isDefault: false
    type: testdata
  - name: gdev-prometheus
    uid: gdev-prometheus
    isDefault: true
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9025
    basicAuth: true #username: admin, password: admin
    basicAuthUser: admin
    jsonData:
      prometheusType: Prometheus #Cortex | Mimir | Prometheus | Thanos
      prometheusVersion: 3.2.1
    secureJsonData:
      basicAuthPassword: admin #https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables
