apiVersion: 1

datasources:
  - name: gdev-testdata
    isDefault: false
    type: testdata
  - name: gdev-prometheus
    uid: gdev-prometheus
    isDefault: true
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9025
    basicAuth: true #username: admin, password: admin
    basicAuthUser: admin
    jsonData:
      manageAlerts: true
      alertmanagerUid: gdev-alertmanager
      prometheusType: Prometheus #Cortex | Mimir | Prometheus | Thanos
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: gdev-tempo
    secureJsonData:
      basicAuthPassword: admin #https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables
